### PR TITLE
[WIP] fix current count

### PR DESCRIPTION
**Pull request by Zeromax**
Started to fix the Count of the values.
For now only the whole result is counted because of a wrong SQL querry.

It has no effect to used values -> The Count for used values is the same at the Moment.
I have added the alias Array because i didn't get it combined in the template otherwise.

For further information see #26

### CODE REVIEW

**Comment by Zeromax** [comment]
Ok So i am a Little bit confused...
I have debugged into it and I do not get the Point.

It is broken since adding the AttributeTypeFactory
-> If I remove this line, everything works like expected: https://github.com/MetaModels/attribute_tags/commit/52dbbef3295eb491fe024dc5a3b1094464330b60#diff-4d64a2c877efc0798cb41ba56192a614R74

So please @discordier @stefanheimes help me with that issue...

**Comment by discordier** [comment]
Found the problem. Will fix as soon as I got rid of my illness.
The query does only fetch the amount and not the item id.

**Comment by Zeromax** [comment]
@discordier So Get well soon ;).

Just for a further Explanation. The fix I proposed above is not the solution for the real Problem. I do not now what has changed in the Tags handling. But the reason why it counts wrong in all cases used tags and not used tags leads back to the `createInstance` function in `AttributeTypeFactory`.

IMHO the wrong class is loaded there. @stefanheimes has added this class and I do not get it why there is the `MetaModelTags` loaded.
```php
public function createInstance($information, $metaModel)
{
    if (substr($information['tag_table'], 0, 3) === 'mm_') {
        return new MetaModelTags($metaModel, $information);
    }

    return new Tags($metaModel, $information);
}
```
See the commit from @stefanheimes 52dbbef #diff-4d64a2c877efc0798cb41ba56192a614R74

So if I do not return the `new MetaModelTags($metaModel, $information);` everything works like expected: The Tags Count is correct for used tags. And so on....

Hopefully i explained it right... ;)

**Comment by Zeromax** [comment]
Btw: That's the reason why i said:
> evtl. nur ein Logik Problem, der Code ist ja noch da ;)

https://github.com/MetaModels/attribute_tags/issues/26#issuecomment-74271738

**Comment by Zeromax** [comment]
The Count is partial fixed with @discordier commit 65d061d

**Pull request closed without merging**
