### PR TITLE
Translated alias didn't work in filter

### PR DESCRIPTION
**Pull request by psren**
fixes https://github.com/MetaModels/core/issues/766

Fix from @cboelter
Seems to work for me.

### CODE REVIEW

**Comment by discordier** [comment]
Could you please fix up the code style issues?
Will have a look at the PR asap.

**Comment by psren** [comment]
Uuups, yeah, of course.
Which code style do i have to apply?

**Comment by cboelter** [comment]
I am using the phpcq / cca code style. On the cca website is a ruleset for phpstorm.

**Comment by cboelter** [comment]
You have also add the author information.

**Comment by psren** [comment]
Code style seems to be correct now. Travis fails with

```
BUILD FAILED
/home/travis/build/MetaModels/attribute_tags/vendor/phpcq/phpcq/tasks/author-validation/task.xml:16: exec returned: 1
Total time: 19 seconds
The command "ant -keep-going" exited with 1.
```

**Comment by cboelter** [comment]
´´´
author-validation:

[author-validation] The file /home/travis/build/MetaModels/attribute_tags/src/MetaModels/Filter/Rules/FilterRuleTags.php is not mentioning its author(s):

[author-validation] ph <ph@wacg.de>

Target 'author-validation' failed with message 'exec returned: 1'.

Cannot execute 'verify' - 'author-validation' failed or was not executed.
´´´
You have to add your information in this file: https://github.com/MetaModels/attribute_tags/blob/tng/.check-author.yml
There you can define a mapping for your data.

**Comment by psren** [comment]
Mhh it still fails.

**Comment by cboelter** [comment]
@psren there is an error in the author validation:

You have to add "ph <ph@wacg.de>" to the mapping not Patrick Heller twice.
https://github.com/psren/attribute_tags/blob/fix-766/.check-author.yml#L19

There is another error in this file: https://github.com/psren/attribute_tags/blob/fix-766/src/MetaModels/Filter/Rules/FilterRuleTags.php#L12-L19
You have to add yourself to the author block of the file not for the class.

**Comment by psren** [comment]
Yeah, it turns green. Thanks for your help. I havn't seen the author-check thing before.

**Pull request merged**
